WITH ONE_GEN AS (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL),
SECOND_GEN AS (SELECT DISTINCT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT * FROM ONE_GEN))
SELECT DISTINCT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT * FROM SECOND_GEN) ORDER BY ID
; 