WITH FEE_TABLE AS (
    SELECT CAR_ID, DAILY_FEE, C.CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단','SUV')
    AND P.DURATION_TYPE = '30일 이상'
)

SELECT DISTINCT F.CAR_ID, F.CAR_TYPE, ROUND(F.DAILY_FEE*30*(1-F.DISCOUNT_RATE/100),0) AS FEE
FROM FEE_TABLE F
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON F.CAR_ID = H.CAR_ID
AND H.START_DATE <= '2022-11-30'
AND H.END_DATE >= '2022-11-01'
WHERE H.CAR_ID IS NULL
AND ROUND(F.DAILY_FEE*30*(1-F.DISCOUNT_RATE/100),0) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC
;