WITH A AS (
SELECT * FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE "Intact%")

SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS OUTS
JOIN A
ON A.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME NOT LIKE "Intact%" 
ORDER BY 1
;