-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID=OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE "intact%" 
AND (OUTS.SEX_UPON_OUTCOME LIKE "Neutered%" OR OUTS.SEX_UPON_OUTCOME LIKE "Spayed%")
ORDER BY OUTS.ANIMAL_ID
;