WITH T AS (SELECT * FROM ONLINE_SALE WHERE USER_ID IN (SELECT DISTINCT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021))

SELECT 
YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PURCHASED_RATIO
FROM T
GROUP BY 1,2
ORDER BY 1,2
;
