WITH T1 AS (SELECT * FROM ONLINE_SALE WHERE USER_ID IN (SELECT DISTINCT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021))

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS 
,ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PURCHASED_RATIO
FROM T1
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;

# SELECT YEAR(SALES_DATE) YEAR,
#        MONTH(SALES_DATE) MONTH,
#        COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
#        ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(USER_ID) 
#                                         FROM USER_INFO
#                                         WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE S
# JOIN USER_INFO I
#     ON S.USER_ID = I.USER_ID
# WHERE I.JOINED LIKE '2021%'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH