WITH RECURSIVE T1 AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D1.ID, D1.PARENT_ID, T1.GENERATION + 1
    FROM ECOLI_DATA D1
    JOIN T1
    ON D1.PARENT_ID = T1.ID
)

SELECT COUNT(DISTINCT T1.ID) AS COUNT, GENERATION
FROM T1
LEFT JOIN ECOLI_DATA D2
ON T1.ID = D2.PARENT_ID
WHERE D2.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION
;