WITH A AS (SELECT PRODUCT_ID, AMOUNT
FROM FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05")

SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(PRO.PRICE*A.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO
JOIN A
ON PRO.PRODUCT_ID = A.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC
;