-- 코드를 입력하세요
SELECT APNT_NO,	PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 04 AND DAY(APNT_YMD) = 13 AND 
APNT_YMD LIKE "%2022-04-13%" AND D.MCDP_CD = "CS" AND APNT_CNCL_YN = "N"
ORDER BY APNT_YMD 
;