-- 코드를 입력하세요
WITH RECURSIVE T_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM T_TABLE WHERE HOUR < 23
)
SELECT T_TABLE.HOUR, IFNULL(REAL_TABLE.COUNT,0) AS COUNT
FROM (SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT 
           FROM ANIMAL_OUTS
           GROUP BY HOUR
     ) AS REAL_TABLE
RIGHT JOIN T_TABLE
ON T_TABLE.HOUR = REAL_TABLE.HOUR
ORDER BY HOUR
;