WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM T WHERE HOUR < 23
)

SELECT T.HOUR, IFNULL(COUNT,0)
FROM T
LEFT JOIN
(SELECT DATE_FORMAT(DATETIME, "%H") AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY 1
ORDER BY 1) A
ON T.HOUR =  A.HOUR
ORDER BY HOUR
;