WITH GT AS
(SELECT G.EMP_NO,
CASE
WHEN AVG(SCORE) >= 96 THEN "S"
WHEN AVG(SCORE) >= 90 AND AVG(SCORE) <96 THEN "A"
WHEN AVG(SCORE) >= 80 AND AVG(SCORE) <90 THEN "B"
ELSE "C" END AS GRADE
FROM HR_GRADE G
GROUP BY G.EMP_NO
ORDER BY 1)

SELECT GT.EMP_NO, E.EMP_NAME, GT.GRADE, 
CASE
WHEN GRADE = "S" THEN SAL*0.2
WHEN GRADE = "A" THEN SAL*0.15
WHEN GRADE = "B" THEN SAL*0.1
ELSE 0 END AS BONUS
FROM GT
LEFT JOIN HR_EMPLOYEES E
ON GT.EMP_NO = E.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP_NO
;
