WITH A AS (
SELECT E.EMP_NO, EMP_NAME, 
    CASE 
    WHEN AVG(SCORE) >= 96 THEN "S"
    WHEN AVG(SCORE) >= 90 THEN "A"
    WHEN AVG(SCORE) >= 80 THEN "B"
    ELSE "C" END AS GRADE, 
    SAL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
    )
SELECT
A.EMP_NO, A.EMP_NAME, A.GRADE,
CASE 
WHEN GRADE ="S" THEN A.SAL * 0.2
WHEN GRADE ="A" THEN A.SAL * 0.15
WHEN GRADE ="B" THEN A.SAL * 0.1
ELSE 0 END AS BONUS
FROM A
ORDER BY 1
;