-- 코드를 입력하세요
WITH ID_LIST AS (
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (
    SELECT MAX(COUNT_REVIEW) FROM (SELECT MEMBER_ID, COUNT(*) AS COUNT_REVIEW
                                    FROM REST_REVIEW
                                    GROUP BY MEMBER_ID) 
    AS SUBQUERY)
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
JOIN ID_LIST ON R.MEMBER_ID = ID_LIST.MEMBER_ID
ORDER BY 3, 2
;