SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (SELECT DISTINCT TREE.ITEM_ID
                 FROM ITEM_INFO INFO
                 JOIN ITEM_TREE TREE
                 ON TREE.PARENT_ITEM_ID = INFO.ITEM_ID
                 WHERE INFO.RARITY = 'RARE')
ORDER BY ITEM_ID DESC;