-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR AS FLAVOR
FROM ICECREAM_INFO JOIN FIRST_HALF ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
WHERE TOTAL_ORDER>=3000 AND INGREDIENT_TYPE = "fruit_based"
ORDER BY TOTAL_ORDER DESC;
;