-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS 
ON CAR.CAR_ID=HIS.CAR_ID
WHERE MONTH(HIS.START_DATE) = 10 AND CAR.CAR_TYPE = "세단"
ORDER BY CAR.CAR_ID DESC
;