SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) AS MAX_INFO
ON MAX_INFO.FISH_TYPE=I.FISH_TYPE AND I.LENGTH=MAX_INFO.MAX_LENGTH
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE=N.FISH_TYPE
ORDER BY ID
;