-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN  (
SELECT CATEGORY, MAX(PRICE) AS MP FROM FOOD_PRODUCT WHERE CATEGORY IN ('과자', '국', '김치', '식용유') GROUP BY CATEGORY) AS MFP
ON FP.CATEGORY = MFP.CATEGORY AND FP.PRICE = MFP.MP 
ORDER BY MAX_PRICE DESC
;