WITH A AS (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT WHERE CATEGORY IN ('과자', '국', '김치', '식용유') GROUP BY CATEGORY)

SELECT A.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN A
ON A.MAX_PRICE = F.PRICE
GROUP BY F.CATEGORY
HAVING F.CATEGORY = A.CATEGORY
ORDER BY MAX_PRICE DESC
;